#!/usr/bin/env python3
import os
import sys
import optparse
import subprocess
import urllib.request

from core import cif_file
from core import supercell
from core import tool
from core import salmon_file

dir_templates = os.path.join(os.curdir, "templates")
dir_pptbl = os.path.join(os.curdir, "pptables")


def main():

    parser = optparse.OptionParser(
        usage="""usage: %prog [options] < ciffile.cif > salmonfile.inp"""
    )
    
    parser.add_option("-p", "--pptype", dest="pptype", type=str,
                      default="abinit-fhi", help="Type of Pseudopotentials ")
    parser.add_option("-t", "--template", dest="template", type=str,
                      default="gs_rt_response", help="Calculation mode")
    parser.add_option("--np", dest="np", type=int,
                      default=150, help="Number of grid inside R_cutoff")
    parser.add_option("--export-cif", dest="export_cif", type=str,
                      default="", help="Export CIF file of generated supercell")
    parser.add_option("-d", "--download", dest="download", action='store_true',
                      default=False, help="Download pseudopotential")
    opts, args = parser.parse_args()

    if os.path.isfile(opts.template):
        file_template = opts.template
    else:
        file_template = os.path.join(dir_templates, "%s.inp" % opts.template)

    pptbl = os.path.join(dir_pptbl, "%s.json" % opts.pptype)

    cif = cif_file.CIF()
    cif.loads(sys.stdin.read())

    a_orth, site_pos, site_lbl = supercell.search_supercell(
        cif.a_prim, cif.site_pos, cif.site_lbl
    )

    if opts.export_cif:
        cif2 = cif_file.CIF(cif.sysname, a_orth, site_lbl, site_pos)
        with open(opts.export_cif, "w") as fh_cif:
            fh_cif.write(cif2.dumps())
    
    salmon = salmon_file.Salmon(
        file_template, cif.sysname, a_orth, site_lbl, site_pos, pptbl, opts.np
    )
    

    sys.stdout.write('! %s\n!\n' % cif.sysname)
    sys.stdout.write('! This input is automatically generated by cif2salmon\n')
    sys.stdout.write('!\n')
    sys.stdout.write('! Required pseudopotentials:\n')
    for item in salmon.pp_url:
        sys.stdout.write('! * %s\n' % item[0])
    sys.stdout.write('!\n\n')
    sys.stdout.write(salmon.dumps())
    
    if opts.download:
        for url in salmon.pp_url:
            sys.stderr.write('! Downloading %s\n' % url[0])
            urllib.request.urlretrieve(url[0], url[1])



if __name__ == "__main__":
    main()
